name: Load books
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r book_loader/requirements.txt
      - name: Run main script
        id: run-main-script
        run: |
          python book_loader/load_books.py
      - name: Commit changes
        id: commit-changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: personalLibrary/src/assets/books.json
          commit_message: "data: update books"
